version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mcp-gateway-db
    restart: always
    environment:
      POSTGRES_USER: mcp-gateway
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mcp-gateway
    ports:
      - "5439:5432"
    volumes:
      - postgres-mcp-gateway-data:/var/lib/postgresql/data
    networks:
      - mcp-gateway-network

networks:
  mcp-gateway-network:
    driver: bridge

volumes:
  postgres-mcp-gateway-data: 