basePath: /
definitions:
  storage.AttributeToRolesConfig:
    properties:
      attribute_key:
        type: string
      attribute_value:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  storage.ObjectType:
    enum:
    - tools
    - '*'
    type: string
    x-enum-varnames:
    - ObjectTypeTools
    - ObjectTypeAll
  storage.PermissionConfig:
    properties:
      object_name:
        type: string
      object_type:
        $ref: '#/definitions/storage.ObjectType'
      proxy:
        type: string
    type: object
  storage.ProxyAuthType:
    enum:
    - header
    - oauth
    type: string
    x-enum-varnames:
    - ProxyAuthTypeHeader
    - ProxyAuthTypeOAuth
  storage.ProxyConfig:
    properties:
      authType:
        $ref: '#/definitions/storage.ProxyAuthType'
      headers:
        items:
          $ref: '#/definitions/storage.ProxyHeader'
        type: array
      name:
        type: string
      oauth:
        $ref: '#/definitions/storage.ProxyOAuth'
      timeout:
        $ref: '#/definitions/time.Duration'
      type:
        $ref: '#/definitions/storage.ProxyType'
      url:
        type: string
    type: object
  storage.ProxyHeader:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  storage.ProxyOAuth:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
      scopes:
        type: string
      tokenEndpoint:
        type: string
    type: object
  storage.ProxyType:
    enum:
    - streamable-http
    type: string
    x-enum-varnames:
    - ProxyTypeStreamableHTTP
  storage.RoleConfig:
    properties:
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/storage.PermissionConfig'
        type: array
    type: object
  time.Duration:
    enum:
    - -9223372036854775808
    - 9223372036854775807
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    type: integer
    x-enum-varnames:
    - minDuration
    - maxDuration
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
info:
  contact:
    name: Source Code
    url: https://github.com/matthisholleville/mcp-gateway
  description: This is the MCP Gateway API documentation.
  title: MCP Gateway API
  version: "1.0"
paths:
  /v1/admin/attribute-to-roles:
    get:
      consumes:
      - application/json
      description: Get all attribute to roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.AttributeToRolesConfig'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Get all attribute to roles
      tags:
      - attribute to roles
    put:
      consumes:
      - application/json
      description: Upsert a attribute to role
      parameters:
      - description: Attribute to role
        in: body
        name: attributeToRole
        required: true
        schema:
          $ref: '#/definitions/storage.AttributeToRolesConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.AttributeToRolesConfig'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Upsert a attribute to role
      tags:
      - attribute to roles
  /v1/admin/attribute-to-roles/{attributeKey}/{attributeValue}:
    delete:
      consumes:
      - application/json
      description: Delete a attribute to role
      parameters:
      - description: Attribute key
        in: path
        name: attributeKey
        required: true
        type: string
      - description: Attribute value
        in: path
        name: attributeValue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Delete a attribute to role
      tags:
      - attribute to roles
  /v1/admin/proxies:
    get:
      consumes:
      - application/json
      description: Get all proxies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.ProxyConfig'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Get all proxies
      tags:
      - proxies
  /v1/admin/proxies/{name}:
    delete:
      consumes:
      - application/json
      description: Delete a proxy
      parameters:
      - description: Proxy name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Delete a proxy
      tags:
      - proxies
    get:
      consumes:
      - application/json
      description: Get a proxy
      parameters:
      - description: Proxy name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.ProxyConfig'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Get a proxy
      tags:
      - proxies
    put:
      consumes:
      - application/json
      description: Upsert a proxy
      parameters:
      - description: Proxy
        in: body
        name: proxy
        required: true
        schema:
          $ref: '#/definitions/storage.ProxyConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.ProxyConfig'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Upsert a proxy
      tags:
      - proxies
  /v1/admin/roles:
    get:
      consumes:
      - application/json
      description: Get all roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.RoleConfig'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Get all roles
      tags:
      - roles
    put:
      consumes:
      - application/json
      description: Upsert a role
      parameters:
      - description: Role
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/storage.RoleConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.RoleConfig'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Upsert a role
      tags:
      - roles
  /v1/admin/roles/{role}:
    delete:
      consumes:
      - application/json
      description: Delete a role
      parameters:
      - description: Role
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Authentication: []
      summary: Delete a role
      tags:
      - roles
schemes:
- http
- https
securityDefinitions:
  Authentication:
    in: header
    name: X-API-Key
    type: apiKey
swagger: "2.0"
