# MCP Gateway configuration

# CORS
cors:
  enabled: true
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
  allow_credentials: true

# Server
server:
  url: "http://localhost:8082"

# OAuth
oauth:
  enabled: true
  provider: "okta"
  authorization_servers:
    - "${OKTA_ISSUER}"
  bearer_methods_supported:
    - "header"
  scopes_supported:
    - "openid"

# Okta
okta:
  issuer: "${OKTA_ISSUER}"
  org_url: "${OKTA_ORG_URL}"
  client_id: "${OKTA_CLIENT_ID}"
  private_key: "${OKTA_PRIVATE_KEY}"
  private_key_id: "${OKTA_PRIVATE_KEY_ID}"

# Auth
auth:
  claims: ["groups"]
  mappings:
    # claim name:group name -> scope name
    "groups:Base": ["scope:1"]
  permissions:
    "*": ["scope:1"]

  options:
    scope_mode: "any" # OR logic. Any is the user has at least one of the scopes. All is the user has all the scopes.
    default_scope: null # deny by default
    enabled: true

# Proxy
proxy:
  servers:
    - name: "n8n"
      type: "streamable-http"
      connection:
        url: "${N8N_URL}"
        timeout: 30s
      auth:
        type: "header"
        header: "x-n8n-key"
        value: "${N8N_PROXY_KEY}"
  proxy_config:
    # Cache for tools and schemas to avoid repeated calls
    cache_ttl: 300s # 5 minutes
    heartbeat:
      enabled: true
      interval_seconds: 10
