DROP TABLE IF EXISTS role_permission CASCADE;
DROP TABLE IF EXISTS attribute_to_roles CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS proxy_oauth CASCADE;
DROP TABLE IF EXISTS proxy_header CASCADE;
DROP TABLE IF EXISTS proxy CASCADE;
DROP SCHEMA IF EXISTS mcp_gateway CASCADE;